/**
 * Reserved usernames for recognizable football players and coaches.
 * Covers last names (when distinctive enough) + firstname+lastname combos + nicknames.
 * Prevents username squatting on real people's identities.
 *
 * Checked case-insensitively; do not include spaces (usernames can't have them).
 */
const RESERVED: string[] = [
  // ─── Global icons ───
  'messi', 'leomessi', 'lionelmessi',
  'ronaldo', 'cr7', 'cristiano', 'cristianoronaldo',
  'mbappe', 'kylianmbappe',
  'neymar', 'neymarjr',
  'haaland', 'erling', 'erlinghaaland',
  'benzema', 'karimebenzema',
  'lewandowski', 'robertlewandowski',
  'modric', 'lukamodric',
  'kroos', 'tonikroos',
  'xavi', 'xavihernandez',
  'iniesta', 'andrésiniesta', 'andresiniesta',
  'busquets', 'sergiobusquets',
  'rooney', 'waynerooney',
  'gerrard', 'stevengerrard',
  'lampard', 'frankhlampard', 'franklampard',
  'henry', 'thieryhenry', 'thierryhenry',
  'zidane', 'zinadine', 'zinedine', 'zinedinezidane',
  'beckham', 'davidbeckham',
  'figo', 'luisfigo',
  'ronaldinho', 'r10',
  'kaka', 'r10kaka',
  'pele', 'edsonpele',
  'maradona', 'diegomaradona',
  'cruyff', 'johancruyff',
  'ibrahimovic', 'zlatan', 'zlatanibrahimovic',
  'drogba', 'diddyDrogba', 'didierdrogba',
  'shevchenko', 'andriy',
  'cantona', 'ericcantona',
  'vieira', 'patrickviera', 'patrickvieira',
  'pirlo', 'andreapirlo',
  'totti', 'francescototti',
  'delpiero', 'alessandrodelpiero',
  'buffon', 'gianluigibuffon',

  // ─── Premier League ───
  // Arsenal
  'saka', 'bukayo', 'bukayosaka',
  'odegaard', 'martin', 'martinodegaard',
  'martinelli', 'gabriel', 'gabrielmartinelli',
  'havertz', 'kai', 'kaiFernandez', 'kaihavertz',
  'calafiori', 'riccardo', 'riccardocalafiori',
  'timber', 'jurrien', 'jurrientimber',
  'white', 'benjaminwhite', 'benwhite',
  'raya', 'davidraya',
  'partey', 'thomaspartey',
  'merino', 'mikelmerino',
  'nwaneri', 'ethan', 'ethannwaneri',
  'saliba', 'williamSaliba',
  // Man City
  'foden', 'phil', 'philfoden',
  'doku', 'jeremy', 'jeremydoku',
  'gvardiol', 'josko', 'joskogvardiol',
  'grealish', 'jack', 'jackgrealish',
  'kovacic', 'mateo', 'mateokovacic',
  'rodri', 'rodrigo',
  'ederson', 'edersonmoraes',
  'walker', 'kylewalker',
  'dias', 'rubendias',
  'stones', 'johnstones',
  'gundogan', 'ilkay', 'ilkaygundogan',
  'debruyne', 'kevin', 'kevindebruyne',
  // Liverpool
  'salah', 'mo', 'mohamedsalah',
  'vandijk', 'virgil', 'virgilVandijk', 'virgilVanDijk',
  'nunez', 'darwin', 'darwinnunez',
  'gravenberch', 'ryan', 'ryangravenberch',
  'szoboszlai', 'dominik', 'dominikszoboszlai',
  'macallister', 'alexis', 'alexismacallister',
  'alisson', 'alissonbecker',
  'robertson', 'andrewrobertson', 'andyrobertson',
  'alexander-arnold', 'trent', 'trentaa', 'taa',
  'jota', 'diogo', 'diogojota',
  'luisdiaz', 'lucho',
  'gakpo', 'codyGakpo',
  'elliott', 'harveyelliott',
  // Man Utd
  'rashford', 'marcus', 'marcusrashford',
  'fernandes', 'bruno', 'brunofernandes',
  'mainoo', 'kobbie', 'kobiemainoo', 'kObbiemainoo',
  'hojlund', 'rasmus', 'rasmushojlund',
  'martinez', 'lisandro', 'lisandromartinez',
  'casemiro',
  'onana', 'andrejsonana', 'andreonana',
  'amad', 'amaddiallo',
  // Chelsea
  'palmer', 'cole', 'colepalmer',
  'mudryk', 'mykhaylo', 'mykhaylomudryk',
  'nkunku', 'christopheNkunku', 'christophenkunku',
  'guiu', 'marcguiu',
  'james', 'reeceJames', 'reecejames',
  'chilwell', 'benchilwell',
  'caicedo', 'moises', 'moisescaicedo',
  'enzo', 'enzoFernandez',
  // Newcastle
  'trippier', 'kieran', 'kierantrippier',
  'isak', 'alexanderisak',
  'gordon', 'anthonygordon',
  'tonali', 'sandrotonali',
  'guimaraes', 'brunoguimaraes',
  // Spurs
  'son', 'sonheungmin',
  'maddison', 'jamesmaddison',
  'bentancur', 'rodrigobentancur',
  'bissouma', 'yves', 'yvebissouma',
  // Aston Villa
  'watkins', 'olliewatkins',
  'coutinho', 'phillipecoutinho',
  'buendia', 'emibUendia', 'emibuendia',
  'kamara', 'boubacar', 'bouphamanKamara',
  'mcginn', 'johnmcginn',
  // West Ham
  'bowen', 'jarrodb', 'jarrodbowen',
  'paqueta', 'lucas', 'lucasPaqueta',
  'kudus', 'mohamedkudus',
  // Brighton
  'mitoma', 'kaoruMitoma',
  'Pedro', 'joaoPedro', 'joãopedro',
  'welbeck', 'dannywelbeck',
  // Leicester / Wolves / Other PL
  'eze', 'ebereeze',
  'olise', 'michael', 'michaelolise',
  'madueke', 'noniMadueke',
  'trossard', 'leandreTrossard',
  'cunha', 'mateus', 'mateuscunha',
  'hwang', 'hwangheecan',
  // Goalkeepers
  'pickford', 'jordanPickford',

  // ─── La Liga ───
  'vinicius', 'vinijr', 'viniciusjunior',
  'bellingham', 'jude', 'judebellingham',
  'rodrygo', 'rodrygosaves',
  'valverde', 'fede', 'federicovalverde',
  'camavinga', 'eduardo', 'eduardocamavinga',
  'tchouameni', 'aurelien', 'aurelientchouameni',
  'courtois', 'thibaut', 'thibautcourtois',
  'militao', 'eder', 'edermilitao',
  'carvajal', 'danielcarvajal',
  'pedri', 'pedrigo', 'pedrigonzalez',
  'yamal', 'lamine', 'lamineyamal',
  'raphinha', 'raphinhadiaz',
  'daniOlmo', 'daniolmo',
  'tersteren', 'marcTerStegen', 'terstegen',
  'griezmann', 'antoine', 'antoinegriezmann',
  'morata', 'alvaro', 'alvaro-morata',
  'depaul', 'rodrigodepaul',
  'simeone', 'giovannisimeone',

  // ─── Bundesliga ───
  'neuer', 'manuelneuer',
  'muller', 'thomas', 'thomasmuller',
  'kimmich', 'joshuakimmich',
  'goretzka', 'leon', 'leongoretzka',
  'sane', 'leroy', 'leroysane',
  'gnabry', 'serge', 'sergegnabry',
  'musiala', 'jamal', 'jamalmusiala',
  'kane', 'harry', 'harrykane',
  'wirtz', 'florian', 'florianwirtz',
  'xhaka', 'granit', 'granitxhaka',
  'boniface', 'victor', 'victorboniface',
  'tah', 'jonathan', 'jonathantah',
  'adeyemi', 'karimadeyemi',
  'sabitzer', 'marcelsabitzer',
  'demirbay', 'kevelindemirbay',
  'hofmann', 'jonashofmann',

  // ─── Serie A ───
  'donnarumma', 'gianluigi', 'gigidonnarumma',
  'barella', 'nicolo', 'nicolobarella',
  'bastoni', 'Alessandro', 'alessandrobastoni',
  'calhanoglu', 'hakan', 'hakancalhanoglu',
  'lautaro', 'lautaromartinez',
  'thuram', 'marcusthuram',
  'pulisic', 'christian', 'christianpulisic',
  'osimhen', 'victor', 'victorosimhen',
  'kvaratskhelia', 'khvicha', 'kvara',
  'dilorenzo', 'giovannidilorenzo',
  'reijnders', 'tijnreijnders',
  'leao', 'rafaelleao',
  'morata', 'alvaromorata',
  'chiesa', 'federicochesa', 'federicochiesA',
  'vlahovic', 'dusanvlahovic',
  'bremer', 'gleissonbremer',

  // ─── Ligue 1 ───
  'lacazette', 'alexandrelacazette',
  'guendouzi', 'matteoguendouzi',
  'nkunku', 'christophenkunku',
  'payet', 'dimitripayet',
  'veretout', 'jordanveretout',
  'okoye', 'madukaokoye',
  'kolo-muani', 'randalkolomuani', 'kolomuani',
  'zaire-emery', 'warrenZaireEmery', 'zaireemery',
  'dembele', 'ousmane', 'ousmanedembele',
  'asensio', 'marcoasensio',

  // ─── International icons ───
  'lukaku', 'romelu', 'romeluLukaku',
  'de-bruyne', 'nainggolan', 'hazard', 'edenhazard',
  'pogba', 'paul', 'paulpogba',
  'kante', 'ngolo', 'ngolokante',
  'varane', 'raphael', 'raphaelvarane',
  'lloris', 'hugolloris',
  'giroud', 'oliviergiroud',
  'dembele', 'mouctar',
  'de-ligt', 'matthijsdeLigt', 'deLigt',
  'depay', 'memphisdepay', 'memphis',
  'de-vrij', 'devij',
  'dumfries', 'denzeldumfries',
  'barella', 'nicolobarella',
  'jorginho',
  'verratti', 'marcoVerratti',
  'insigne', 'lorenzinsigne',
  'immobile', 'ciroimmobile',
  'chiellini', 'giorgiochiellini',
  'bonucci', 'leonardobonucci',
  'de-rossi', 'daniloDeRossi', 'daniloDeRossiCoach',
  'nainggolan', 'radijanatinGolan',
  'de-gea', 'davidDeGea', 'degea',
  'ramos', 'sergio', 'sergioramos',
  'alba', 'jordialba',
  'busquets', 'sergiobusquets',
  'pique', 'gerardpique',
  'suarez', 'luis', 'luissuarez',
  'neymarjr', 'nj11',
  'aguero', 'kun', 'kunaguero', 'sergiOaguero',
  'silva', 'thiago', 'thiAgosilva', 'thiagosilva',
  'david-luiz', 'davidLuiz',
  'alves', 'danielalves', 'daniAlves',
  'hulk', 'givanilton',
  'oscar', 'oscarDossantos',
  'firmino', 'robertofirmino', 'bobby',
  'coutinho', 'philippecoutinho',
  'coman', 'kingsleycoman',
  'hernandez', 'lucasthernandez', 'theoHernandez',
  'upamecano', 'dayotUpamecano',
  'pavard', 'benjaminPavard',
  'navas', 'keplernAvas', 'keplernavas',
  'navas', 'jesusnavas',
  'correa', 'angelcorrea',
  'llorente', 'marcosllorente',
  'saul', 'saullniguez', 'saulNiguez',
  'oblak', 'janOblak',
  'joao-felix', 'joaofelix',
  'joao-cancelo', 'joaocancelo', 'cancelo',
  'ruben-neves', 'rubenneves',
  'neves', 'rubenNeves',
  'pepe', 'keplerlaverde',
  'bernardo', 'bernardosilva',
  'joao-moutinho', 'joaomoutinho',
  'diogo-jota', 'diogojota',
  'felix', 'joaofelix',
  'matheus-nunes', 'matheusNunes',
  'vitinha', 'vitorferreira',
  'zahavi', 'ejzahavi',
  'eriksen', 'christianeriksen',
  'dolberg', 'kasperdolberg',
  'de-ligt', 'matthjsdeLigt',
  'blind', 'daleyblind',
  'stekelenburg', 'maartenstek',
  'strootman', 'kevinstroot',
  'sneijder', 'wesleysnijder',
  'robben', 'arjenrobben',
  'van-persie', 'robinVanPersie', 'vanPersie',
  'huntelaar', 'klashuntelaar', 'klaashuntelaar',
  'de-jong', 'frenkie', 'frenkiedejong', 'fredejong',
  'van-dijk', 'virgilVanDijk', 'virgilDijk',
  'dumfries', 'denzeldumfries',
  'bergkamp', 'dennisbergkamp',
  'kluivert', 'patrickkluivert',
  'seedorf', 'clarenceseedorf',
  'davids', 'edgardavids',
  'maldini', 'paulomaldini',
  'baresi', 'francobaresi',
  'albertini', 'demetrioalbertini',
  'nesta', 'alessandronesta',
  'costacurta', 'alessandrocosta',
  'sheva', 'andriy',
  'inzaghi', 'filippoInzaghi',
  'crespo', 'hernanCrespo',
  'vieri', 'christianvieri',
  'del-piero', 'alessandrodelpiero',
  'zola', 'gianfrancozola',
  'raul', 'raulGonzalez',
  'hierro', 'fernandoHierro',
  'morientes', 'fernandomorientes',
  'casillas', 'ikerCasillas',
  'xabi', 'xabiAlonso',
  'alonso', 'xabiAlonso',
  'villa', 'davidvilla',
  'torres', 'fernandotorres',
  'fabregas', 'cesc', 'cescFabregas',
  'puyol', 'carlespuyol',
  'abidal', 'ericAbidal',
  'sylvinho', 'silvinhoBraga',
  'pinto', 'joaovictorPinto',
  'zambrotta', 'gianluigiZambro',
  'canavaro', 'fabioCannavaro', 'cannavaro',
  'materazzi', 'marcomaterazi',
  'grosso', 'fabioGrosso',
  'gilardino', 'albertoGilardino',
  'gattuso', 'gennaroGattuso', 'rino',
  'ambrosini', 'massimoAmbrosini',
  'seedorf', 'clarenceSeedorf',
  'kaka', 'ricardoKaka',
  'roberto-carlos', 'robertocarlos',
  'cafu', 'marcos',
  'ronaldo-nazario', 'r9', 'ronaldonazario',
  'rivaldo',
  'romario',
  'adriano', 'adrianoLeite',
  'kakà', 'ricardokaka',

  // ─── Coaches ───
  'guardiola', 'pep', 'pepguardiola',
  'klopp', 'jurgen', 'jurgenklopp',
  'mourinho', 'jose', 'josemourinho', 'thespecialone',
  'ancelotti', 'carlo', 'carloancelotti',
  'simeone', 'diego', 'diegosimeone', 'cholo',
  'wenger', 'arsene', 'arsenewenger',
  'ferguson', 'alexferguson', 'siralexferguson',
  'conte', 'antonio', 'antoniocontee',
  'allegri', 'massimiliano', 'maxallegri',
  'tuchel', 'thomas', 'thomastuchel',
  'nagelsmann', 'julian', 'juliannagelsmann',
  'tenhaag', 'eriktenhaag', 'ten-hag',
  'arteta', 'mikel', 'mikelarteta',
  'slot', 'arne', 'arneslot',
  'maresca', 'enzo', 'enzomaresca',
  'postecoglou', 'ange', 'angepostecoglou',
  'howe', 'eddie', 'eddiehowe',
  'kompany', 'vincent', 'vincentkompany',
  'amorim', 'rui', 'ruiamorim',
  'emery', 'unai', 'unaiemery',
  'lopetegui', 'julen', 'julenlopetegui',
  'pochettino', 'mauricio', 'mauriciopochettino',
  'sarri', 'maurizio', 'mauriziosarri',
  'ranieri', 'claudio', 'claudioranieri',
  'capello', 'fabio', 'fabiocapello',
  'lippi', 'marcello', 'marcelolippi',
  'deschamps', 'didier', 'didierdeschamps',
  'southgate', 'gareth', 'garethsouthgate',
  'flick', 'hansiflick',
  'tedesco', 'domenicotedesco',
  'xabi-alonso', 'xabiAlonsoCoach',
  'de-zerbi', 'robertodezerbi', 'dezerbi',
  'iraola', 'andoniiraola',
  'marmoush', 'omarmarmoush',
  'de-rossi', 'danieleDeRossi',

  // ─── Common handle patterns ───
  'cr7', 'lm10', 'g9', 'r9', 'r10', 'k9',
  'thebest', 'goat', 'thegoat', 'el-goat', 'elgoat',
];

const RESERVED_SET = new Set(RESERVED.map((u) => u.toLowerCase()));

/**
 * Returns true if the username is reserved for a footballer or coach.
 * Check is case-insensitive.
 */
export function isUsernameReserved(username: string): boolean {
  return RESERVED_SET.has(username.toLowerCase().trim());
}
